#if !canImport(ObjectiveC)
import XCTest

extension EmptyResultTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EmptyResultTests = [
        ("testGettingError", testGettingError),
    ]
}

extension KeyValueEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyValueEncoderTests = [
        ("testEncodingObject", testEncodingObject),
    ]
}

extension MakeRequestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MakeRequestTests = [
        ("testEmpty", testEmpty),
        ("testEmptyRequestFlow", testEmptyRequestFlow),
        ("testIgnoringBasicAndErrorResponses", testIgnoringBasicAndErrorResponses),
        ("testIn", testIn),
        ("testInOut", testInOut),
        ("testInOutRequestFlow", testInOutRequestFlow),
        ("testInRequestFlow", testInRequestFlow),
        ("testOut", testOut),
        ("testOutRequestFlow", testOutRequestFlow),
        ("testURLQueryInOutRequestFlow", testURLQueryInOutRequestFlow),
        ("testURLQueryInRequestFlow", testURLQueryInRequestFlow),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EmptyResultTests.__allTests__EmptyResultTests),
        testCase(KeyValueEncoderTests.__allTests__KeyValueEncoderTests),
        testCase(MakeRequestTests.__allTests__MakeRequestTests),
    ]
}
#endif
